### ISSUE TITLE
about Pubmed-shuffle-win-30. bin

### ISSUE THREAD

**Issue by wqx9826** [yahshibu/nested-ner-2019#4]
Hello, thank you for your open source code, but the file Pubmed-shuffle-win-30. bin cannot be downloaded now, could you please provide a copy?

**Comment by yahshibu** [comment]
Thank you for having an interest in our work!

Yes, I can, but it seems like Pubmed-shuffle-win-2.bin is still available [here](https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view?resourcekey=0-hKMdnLPkaFZZYNiIMeyoww). Could you try again? If you still cannot download it, I'll provide a copy in some way.

Thanks.

**Comment by yahshibu** [comment]
Thank you for having an interest in our work!

Yes, I can, but it seems like Pubmed-shuffle-win-2.bin is still available [here](https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view?resourcekey=0-hKMdnLPkaFZZYNiIMeyoww). Could you kindly try again? If you still cannot download it, I'll provide a copy in some way.

Thanks.

**Comment by python-newlearner** [comment]
Yes！ I know it can be downloaded from the Google cloud disk! but I have tried many methods. I don't have permission to access it and can't download it. If it is convenient for you, can you send me a copy by email or in other forms.

**Comment by python-newlearner** [comment]
Yes！ I know it can be downloaded from the Google cloud disk! but I have tried many methods. I don't have permission to access it and can't download it. If it is convenient for you, can you send me a copy by email or in other forms.

**Comment by wqx9826** [comment]
Yes！ I know it can be downloaded from the Google cloud disk! but I have tried many methods. I don't have permission to access it and can't download it. If it is convenient for you, can you send me a copy by email or in other forms.
Thanks

**Comment by yahshibu** [comment]
I see. I copied the file to my Google Drive. Could you try accessing [this](https://drive.google.com/file/d/11m4T0lcwUcdXRllnVk1WR0te0tTR_RY1/view?usp=sharing)?

The file is very large, so it is impossible to attach it to an email. If you cannot access my Google Drive, then I have no idea how to provide it.

**Comment by wqx9826** [comment]
Thank you very much for your help. I have successfully downloaded the materials
